spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    callSettersOnNulls: true
  mapper-locations: classpath*:/mapper/*.xml
rabbitmq:    					        #本地环境不需要配置mq
    host: localhost
    port: 15672
    username: guest
    password: guest
test: test
