spring:
  datasource:
    url: jdbc:oracle:thin:@cdbonc.asuscomm.com:1521:assistantdb
    username: STARCLOUDPORTAL
    password: root.123
    driver-class-name: oracle.jdbc.OracleDriver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: cdbonc.asuscomm.com
    password: bonc!%*cd_qie[yu0ertoigsi
    port: 6379
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    callSettersOnNulls: true
  mapper-locations: classpath*:/mapper/*.xml
test: test
secret: secret
