spring:
  application:
    name: client-ribbon
server:
  port: 2023
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2020/eureka/
#启用监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
